name: datawallet
description: Data Wallet verifier client.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sodium: ^4.0.0
  cbor: ^6.5.1
  http: ^1.6.0
  crypto: ^3.0.7
  flutter_secure_storage: ^9.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
